### ISSUE TITLE
Duplicate download release..

### ISSUE THREAD

**Issue by ne0ark** [autodl-community/autodl-rutorrent#26] opened 2016-08-31 00:02 UTC
This option is getting unchecked if you navigate away from the filter it is selected on. Only option to have it selected is to manage filter manually by editing the .cfg file.

**Comment by Dantrum** [comment] 2016-10-13 19:42
I have the same issue, in fact it's present for all the checkboxes for that a filter.

**Comment by thebigmunch** [comment] 2016-10-22 22:50
So, another user that had this issue did some testing and discovered that it was an issue caused by the Swizards ruTorrent theme. They and some others that have run into this used the QuickBox install script. I'm guessing that's the cause for everyone's issues, so I'll be closing the issue as it's not related to autodl-rutorrent.

**Comment by ne0ark** [comment] 2016-10-22 23:14
This is happening all the themes in rutorrent. I have opened another ticket there hopefully, it will be resolved https://github.com/Novik/ruTorrent/issues/1342 .

**Comment by thebigmunch** [comment] 2016-10-23 00:21
Don't actually know if it's true or not since I've still never been able to reproduce this. That's simply one user's experience. When someone debugs it to the point of finding what the cause is, if not that, they can post it here. I'd start by taking a look at the version of jQuery in use in ruTorrent on your system. You can also check in DialogUtils.js to see if any of the jQuery method behaviors have changed over time.

If I could actually reproduce it anywhere myself, I might actually be able to help. But I can't.

**Comment by Fugor** [comment] 2016-10-23 10:54
Same issue here, I'll do some testing with themes and look at jQuery and come back.

**Comment by thebigmunch** [comment] 2016-10-23 11:10
I ended up giving one last shot at trying to figure out the old Reload button issue. While doing this, I refreshed ruTorrent on my Whatbox slot to their latest fork which I hadn't done in a while. Ran into an unrelated issue with a function being removed in 3.0. So I decided to test this issue. Et voila!. In July, they updated it to use jQuery 3.1. Loaded jquery-migrate into the mix and found 2 or 3 things including the cause of this on newer jQuery versions.

**Comment by thebigmunch** [comment] 2016-10-23 11:20
And, why QuickBox installs are specifically displaying this issue is because they don't stick to release versions of ruTorrent.

**Comment by ne0ark** [comment] 2016-10-23 17:38
Ah 🎱 . The release is from Oct 16, 2013 I also use SVN for bugfixes. Hopefully, the fix is easy. Thank you for debugging.

**Comment by thebigmunch** [comment] 2016-10-23 22:53
Feel free to check out the jquery-updates branch to test out the fixes.

**Comment by ne0ark** [comment] 2016-10-23 23:28
Hmm Issues still there. My browser console says. 

```
$().jquery
"1.11.3"
```

https://github.com/Novik/ruTorrent/blob/master/js/jquery.js also shows 1.11.3.

**Comment by Fugor** [comment] 2016-11-03 11:49
> Feel free to check out the jquery-updates branch to test out the fixes.

I can if you tell me how.

**Comment by thebigmunch** [comment] 2017-01-06 22:56
This issue is resolved with the jQuery updates as far as I can tell on all systems I've tested.

**Closed by thebigmunch** 2017-01-06 22:56 UTC
Labels: bug
